# Generated by Django 2.2.14 on 2020-11-23 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201121_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha_streno',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sipnopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
